//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hardware()
        {
            this.Histoty = new HashSet<Histoty>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual Сonsumables Сonsumables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Histoty> Histoty { get; set; }
        public virtual MainGroup MainGroup { get; set; }
        public virtual OtherHardwares OtherHardwares { get; set; }
        public virtual Printers Printers { get; set; }
    }
}
