//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Histoty
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsEnterUsing { get; set; }
        public int CabinetId { get; set; }
        public int HardwareId { get; set; }
    
        public virtual Cabinets Cabinets { get; set; }
        public virtual Hardware Hardware { get; set; }
    }
}
