//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionDB : DbContext
    {
        public ConnectionDB()
            : base("name=ConnectionDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinets> Cabinets { get; set; }
        public virtual DbSet<Hardware> Hardware { get; set; }
        public virtual DbSet<Histoty> Histoty { get; set; }
        public virtual DbSet<MainGroup> MainGroup { get; set; }
        public virtual DbSet<OtherHardwares> OtherHardwares { get; set; }
        public virtual DbSet<Printers> Printers { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<Сonsumables> Сonsumables { get; set; }
    }
}
