//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printers
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public string TypeCartridge { get; set; }
        public bool HavePrintDoubleList { get; set; }
        public bool IsMFY { get; set; }
    
        public virtual Hardware Hardware { get; set; }
    }
}
